---
title: "EDS 212"
subtitle: "Day 3 Part 2 - Linear algebra fundamentals"  
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

## Linear algebra introduction

Linear algebra "branch of mathematics concerning linear equations" (Wikipedia), sometimes also described as the math of vectors & matrices. 

It is a fundamental part of data science (and how computers understand & process data), and useful for describing environmental processes.

As [Dr. Jason Brownlee](https://machinelearningmastery.com/gentle-introduction-linear-algebra/) writes, "Linear algebra is the mathematics of data."

---

## In environmental data science, most often:

Put your linear equations into a matrix.

---

## The building blocks of linear algebra

- **scalar:** a value without direction, representing magnitude

- **vector:** a list of values, representing magnitude *and* direction or a point in multivariate space

- **matrix:** a table of values

---

## Applications of linear algebra in data science

- Array programming / vectorized code
- Machine learning
- For loops

---

## Applications of linear algebra in environmental sciences

- Dimensional reduction
- Population matrix models
- Optimization

---

## Basic math with scalars & vectors

- Vector addition & subtraction
- Scalar multiplication
- Basic matrix algebra
---

## Vector addition & subtraction



---

