---
title: 'Day 2: Tasks & group activities'
subtitle: 'Derivatives - by hand & in R'
output: 
  html_document:
    css: activities_theme.css
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Section 1: (Small groups) Derive the definition of the derivative

- Put all notes away
- With a partner, based on what you've learned, derive the definition of the derivative from scratch
- At every step, describe *what* you are doing
- Picture drawing is encouraged
- Once you have the definition of the derivative, say out loud (each person) what we're doing mathematically every time we find the derivative

## Section 2: Derivatives by hand

### First order univariate:

1. By hand using the definition of the derivative (i.e., "the long way"), find $\frac{dT}{dq}$ for $T(q)=2-3q^2$

2. By hand and using derivative rules: Find $\frac{dx}{dt}$ for $x(t)=\frac{1}{x^3}+2.4e^{3x}$


### Higher order univariate: 

3. By hand and using derivative rules: Find $\frac{d^3f}{dx^3}$ for $f(x)=4x^5-2x$

### Partial derivatives: 

4. By hand, find all partials of the function: $B(T,p,k)=2T^3-3.5pk^2$

5. For the function above, what is the slope in the $p$ direction at $T = 1.9, k = 2.4$?

## Section 3: Derivatives in R

- Create a new R Project (named `eds-212-day-2`) (or using a naming convention you choose for all EDS 212 projects)
- Create a new R Markdown document in the project
- Attach the `tidyverse` and `palmerpenguins` packages in the setup chunk with `library(package_name)` (note: you may need to install `palmerpenguins` - remember `install.packages("packagename")`)
- Knit (save your .Rmd as `eds212_day2_activities.Rmd`, or follow a naming convention you've decided on)
- Use `usethis::use_git()` and `usethis::use_github()` to make your project a version-controlled repo, with an upstream GitHub repo

### First order univariate derivatives:

- In your R Markdown document, find the derivative expression and slope at the indicated value for each the following functions in R (each in a separate code chunk).

  A) $f(x)=x^2$ at $x = 3$
  B) $P(a)=2(3a+2)^4-5$ at $a = 1.2$
  C) $g(t)=\frac{-4t}{(t^2+1)^3}$ at $t = 0$

- Knit, stage, commit, pull, then push your changes to your repo on GitHub. 

### Higher order univariate derivatives: 

- Back in RStudio, add a code chunk in your Rmd in which you find the second derivative with respect to $z$ for $G(z)=4.6-1.9z^3$. Check your solution by hand. 

- Save (or knit) your .Rmd. Stage, commit, pull, then push all changes to your remote repo. Check that changes are stored on GitHub. 

## Section 4: Make a penguin plot

- In a new code chunk, create a `ggplot` graph of penguin bill length versus bill depth (using the `penguins` dataset in the `palmerpenguins` package), with point color dependent on species. You should attach the `tidyverse` and `palmerpenguins` package in your .Rmd setup chunk. Update labels and add a title.

- In a new code chunk, make a jitterplot of flipper length by species (species on the x-axis, flipper length on the y-axis). Update axis labels and add a title. 

- Knit your .Rmd to check for reproducibibility

- Stage, commit, and push changes to the remote repo. Once you do, go to GitHub and check to see the changes are safely stored & tracked. 

- Go back to your R Markdown document in RStudio. Pull to make sure you have the same versions as in the remote repo. Make a change (anything you want - maybe change your graph colors, sizes, etc.), then stage, commit, & push changes to the remote repo to reinforce the steps. Check that changes are stored on GitHub. 

## End
