---
title: "Day 3 Tasks & Activities"
subtitle: 'Vectors by hand and in R, numerical approximation of ODEs, practicing different git setups'
output: 
  html_document:
    css: activities_theme.css
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 1: By hand problems

### Vector math

For the vectors $\vec a = (1,6)$ and $\vec b = (2, 4)$: 

1. Find and sketch $\vec a + \vec b$
2. Find and sketch $\vec b - \vec a$
3. Find and sketch $4 \vec a$
4. Find $\vec a \cdot \vec b$

### One numerical approximation by hand

5.  Given: $\frac{dP}{dx}=P-0.5$ and an initial value $P(0)=0.3$, approximate the value of P for x values from 0 to 4 (x increasing by increments of 1). Sketch your approximation (P on the vertical axis, x on the horizontal axis)

## Part 2: Coding practice

- Create a new version-controlled R Project using the "GitHub repo *first*" workflow (hint: make a new repo on GitHub named `eds212-day3-part3` with a ReadMe, then clone to link to an R Project...)

- Create a new .Rmd within your project

- Using the `c()` function, create and store two new vectors, called `vec_a` and `vec_b`, where $\vec a = (1,6)$ and $\vec b = (2, 4)$: 

- Check your by-hand solutions from Part 1 by finding the following in R: 

  - $\vec a + \vec b$
  - $\vec b - \vec a$
  - $4 \vec a$
  - $\vec a \cdot \vec b$

## Part 3: Fork & clone a repo, use the code

- Fork and clone [this repo](https://github.com/allisonhorst/eds212-sir-ode), which contains an R Markdown document with code to numerically solve the SIR equations, to create a version-controlled R Project

- Once you've created your R Project, open the `sir-example.Rmd` file. 

- Run all code in the .Rmd (Cmd + Option + R, or go up to the run button and choose the last option "Run All")

- Explore the code and output graph. What is the code doing? What is the graph telling us? 

- Make small changes to the parameter values to see how the SIR models change. Are the changes expected? 

- After trying out a few changes, save and knit your new output graph.

- Stage, commit, pull, then push to your repo.

- Check for your changes on GitHub. Are they there? Cool, done with Part 2.


## End
