---
title: "Day 5: Basic probability theory and Boolean algebra"
description: |
  Review of linear algebra basics, introduction to boolean algebra, and thinking like a computer
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Day 5 Part 1:

```{r, echo = FALSE}
xaringanExtra::embed_xaringan(
  url = "https://allisonhorst.github.io/EDS_212_essential-math/slides/EDS_212_day-5-part-1-slides.html",
  ratio = "16:9",
  border = "1px solid gainsboro"
)
```

#### Flex session

- Start creating your personal website in `distill`

Day 5 Part 2:

```{r, echo = FALSE}
xaringanExtra::embed_xaringan(
  url = "https://allisonhorst.github.io/EDS_212_essential-math/slides/EDS_212_day-5-part-2-slides.html",
  ratio = "16:9",
  border = "1px solid gainsboro"
)
```

#### Flex session

- Personal website continued

## Day 5 Tasks and Activities

### Refresher problems

### Challenge problems

### Creative thinking problems

## Efficiency tips

*Inspired by Dr. Julia Lowndes' [Openscapes](openscapes.org) program.*


