---
title: "EDS 212: Essential Math in Environmental Data Science"
description: "Course materials for EDS 212"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(kableExtra)
# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

## Instructor

Allison Horst (ahorst\@ucsb.edu)

## Important links

-   [Course syllabus](https://docs.google.com/document/d/1Kcc9BhZuKeAGxQeW0ls7KY0oUtt-TBwEgOibl4_ShtY/edit?usp=sharing)
-   EDS Course Workbook
-   Code of Conduct

## Course description

Quantitative skills and understanding are critical when working with, understanding, analyzing and gleaning insights from environmental data. In the intensive EDS 212 course, students will refresh fundamental skills in basic math (algebra, uni- and multivariate functions, units and unit conversions), derivative and integral calculus, differential equations, linear algebra, and reading, writing and evaluating logical operations.

## Predictable daily schedule

**Course dates:** Monday (2021-08-02) - Friday (2021-08-06)

EDS 212 is an intensive 1-week long 2-unit course. Students should plan to attend all scheduled sessions. All course requirements will be completed between 8am and 5pm PST (M - F), i.e. you are not expected to do additional work for EDS 212 outside of those hours, unless you are working with the Teaching Assistant in student hours.

Tentative daily schedule (subject to change):

|                   |                                                            |
|-------------------|------------------------------------------------------------|
| **Time (PST)**    | **Activity**                                               |
| 8:00am - 9:00am   | *Lecture 1 (60 min)*                                       |
| 9:00am - 9:15am   | *Break 1 (15 min)*                                         |
| 9:15am - 10:15am  | *Interactive Session 1 (60 min)*                           |
| 10:15am - 11:00am | *Flex time (45 min)*                                       |
| 11:00am - 12:15pm | *Break 2 (75 min)*                                         |
| 12:15pm - 1:15pm  | *Lecture 2 (60 min)*                                       |
| 1:15pm - 2:15pm   | *Interactive Session 2 (60 min)*                           |
| 2:15pm - 3:15pm   | *Flex time (60 min)*                                       |
| 3:15pm - 5:00pm   | *Interactive Session 3: Group & challenge tasks (105 min)* |

## Learning objectives

The goal of EDS 212 (Essential Math in Environmental Data Science) is to prepare incoming MEDS students with quantitative methods, skills, notation and language commonly used in environmental data science and required for their data science courses and projects in the program. By the end of the course, students should be able to: 

-   **Perform the following by hand and in R:** convert units, basic algebra and working with logs and exponentials; write, interpret and evaluate univariate and multivariate functions; basic derivatives and integrals with univariate and multivariate functions; solve simple differential equations; basic operations with scalars, vectors and matrices; writing and evaluating logicals

-   **Explain and share examples** for how all topics in EDS 212 are useful and used in applied environmental data science

-   **Interpret** examples of applied math & models from environmental science case studies 

-   **Work with peers** to solve group tasks, then **communicate** the process of problem solving to the rest of the class

## Course requirements

### Computing

-   Minimum MEDS device requirements (bring to all sessions)

-   R version 4.0.2 (or higher)

-   RStudio version 1.4.1103 (or higher)
