---
title: "EDS 212"
subtitle: "Day 3 Part 1: Differential equations - reading, understanding, solving numerically in R"  
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

class: center, middle
# EDS 212 Day 3

## Part 1: Differential equations

---

## Introduction to differential equations

A **differential equation** is an equation containing a differential expression

For example: 

$$\frac{df}{dt}=3.2-f(t)$$
is a differential equation because it contains both a the function $f(t)$ and it's derivative, $\frac{df}{dt}$.

---

## Differential equations: terms

- **Ordinary differential equation (ODE):** Does not contain partial derivatives

$$\frac{df}{dt}=3.2-f(t)$$

- **Partial differential equations (PDE):** Does contain partial derivatives

$$\frac{\partial B}{\partial t}= \alpha B+0.31$$
---

## Order of an ODE
- **Order:** The order of a differential equation is the highest order for any differential expression in the equation 

$$\frac{df}{dt}=3.2-f(t)$$ is a **first order ODE** 

---

## Practice: Use the terms from the previous slide to describe the following different equations

1. $\frac{\partial^2f }{\partial x^2}=1.4\times10^{-3}f(x)+5.2$

2. $2.9t^2 - \alpha B=\frac{dB}{dt}$

---

## Differential equations in EDS

---

## Reading and interpreting differential equations

---

## More examples in environmental data science

---

## Solving differential equations in R

### Numerical solutions versus analytical solutions

---

## An example in practice

---



