---
title: "EDS 212"
subtitle: "Day 2: Slopes, derivatives, computation, application"  
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  fig.show = TRUE,
  hiline = TRUE
)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#003660",
  header_font_google = google_font("Sanchez"),
  text_font_google   = google_font("Nunito Sans", "300", "300i"),
  code_font_google   = google_font("Roboto Mono"),
  base_font_size = "18px",
  text_font_size = "26px",
  table_border_color = "#ffffff",
  table_row_border_color = "#ffffff",
  table_row_even_background_color = "ffffff",
  text_slide_number_font_size = "0.7em",
)
```

## Overview of Day 2 topics

- Topic 1
- Topic 2
- Topic 3

---

## Slopes in environmental data science
